#!/usr/bin/env tsx
// scripts/provision-client.ts — Generate per-client deployment artifacts.
// Usage:
//   npx tsx scripts/provision-client.ts \
//     --clientId acme \
//     --companyName "Acme Corp" \
//     --primaryColor "#00cc66" \
//     --whatTheySell "IoT inventory management" \
//     --idealPartner "MSPs serving warehouses and distributors" \
//     --adminEmail admin@acme.com \
//     --cronOffset 30
//
// Outputs (does NOT deploy anything):
//   client-config.json         — local dev config for this client
//   .env.acme                  — all required env vars for this client
//   fly.acme.toml              — Fly.io config for this client's deployment
//
// To deploy:
//   fly deploy --config fly.{clientId}.toml

import fs from "fs";
import path from "path";

// ─── ARG PARSING ─────────────────────────────────────────────────────────────

function parseArgs(argv: string[]): Record<string, string> {
  const result: Record<string, string> = {};
  for (let i = 2; i < argv.length; i++) {
    if (argv[i].startsWith("--")) {
      const key = argv[i].slice(2);
      const value = argv[i + 1] && !argv[i + 1].startsWith("--") ? argv[++i] : "true";
      result[key] = value;
    }
  }
  return result;
}

const args = parseArgs(process.argv);

function require_arg(name: string): string {
  const val = args[name];
  if (!val) {
    console.error(`Error: --${name} is required`);
    process.exit(1);
  }
  return val;
}

const clientId = require_arg("clientId").toLowerCase().replace(/[^a-z0-9-]/g, "-");
const companyName = require_arg("companyName");
const primaryColor = args.primaryColor ?? "#00ff88";
const whatTheySell = require_arg("whatTheySell");
const idealPartner = require_arg("idealPartner");
const adminEmail = require_arg("adminEmail");
const cronOffset = parseInt(args.cronOffset ?? "0", 10);

// ─── CRON SCHEDULE ───────────────────────────────────────────────────────────

const cronHour = 9;
const cronMinute = cronOffset % 60;
const cronSchedule = `${cronMinute} ${cronHour} * * *`;

// ─── client-config.json ──────────────────────────────────────────────────────

const clientConfig = {
  clientId,
  companyName,
  tagline: `${companyName} VAR Prospecting Pipeline`,
  primaryColor,
  website: args.website ?? "",
  whatTheySell,
  idealPartner,
  targetVerticals: [],
  avoidVerticals: [],
  cronSchedule,
  watchtowerConfig: null,
  brandConfig: null,
};

const configPath = path.join(process.cwd(), "client-config.json");
fs.writeFileSync(configPath, JSON.stringify(clientConfig, null, 2));
console.log(`✓ Generated client-config.json`);

// ─── .env.{clientId} ─────────────────────────────────────────────────────────

const envContent = `# VAR Hunter — ${companyName} (${clientId})
# Generated by scripts/provision-client.ts
# Fill in API keys before deploying.

ANTHROPIC_API_KEY=
SERPER_API_KEY=
RESEND_API_KEY=
REPORT_TO_EMAIL=${adminEmail}
RESEND_FROM=reports@${clientId}.var-hunter.io
ENABLE_EMAIL_DELIVERY=false
CRON_SECRET=${crypto.randomUUID()}
TEAMS_WEBHOOK_URL=

# Client identity
CLIENT_ID=${clientId}
CLIENT_COMPANY_NAME=${companyName}
CLIENT_TAGLINE=${companyName} VAR Prospecting Pipeline
CLIENT_PRIMARY_COLOR=${primaryColor}
CLIENT_WEBSITE=${args.website ?? ""}
CLIENT_WHAT_THEY_SELL=${whatTheySell}
CLIENT_IDEAL_PARTNER=${idealPartner}
CLIENT_TARGET_VERTICALS=
CLIENT_AVOID_VERTICALS=
CLIENT_CRON_SCHEDULE=${cronSchedule}

# Future integrations (leave blank until added)
SUPABASE_URL=
SUPABASE_ANON_KEY=
CLERK_PUBLISHABLE_KEY=
CLERK_SECRET_KEY=
INNGEST_EVENT_KEY=
INNGEST_SIGNING_SECRET=
`;

const envPath = path.join(process.cwd(), `.env.${clientId}`);
fs.writeFileSync(envPath, envContent);
console.log(`✓ Generated .env.${clientId}`);

// ─── fly.{clientId}.toml ─────────────────────────────────────────────────────

const flyToml = `# Fly.io config for VAR Hunter — ${companyName} (${clientId})
# Generated by scripts/provision-client.ts

app = "var-hunter-${clientId}"
primary_region = "lax"

[build]

[env]
  NODE_ENV = "production"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

# Daily pipeline run at ${cronSchedule} UTC
[[statics]]

[processes]
  app = "node server.js"

# Cron: ${cronSchedule} UTC (offset ${cronOffset}m from 9am)
# To trigger: curl -H "Authorization: Bearer $CRON_SECRET" https://var-hunter-${clientId}.fly.dev/api/cron
`;

const flyPath = path.join(process.cwd(), `fly.${clientId}.toml`);
fs.writeFileSync(flyPath, flyToml);
console.log(`✓ Generated fly.${clientId}.toml`);

// ─── SUMMARY ─────────────────────────────────────────────────────────────────

console.log(`
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Client provisioned: ${companyName} (${clientId})
  Cron schedule: ${cronSchedule} UTC
  Admin email: ${adminEmail}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Next steps:
  1. Fill in API keys in .env.${clientId}
  2. Set Fly secrets:
       fly secrets import --config fly.${clientId}.toml < .env.${clientId}
  3. Deploy:
       fly deploy --config fly.${clientId}.toml

`);
